### ISSUE TITLE
"No such module" error when importing GoogleAPIClient or GoogleAPIClientForREST

### ISSUE THREAD

**Issue by traviskaenel** [aytek/iOS-Swift-Google-Drive-Document-Picker#2]
I would very much appreciate it if you took a look at my question [here]. For some reason I get an error when importing GoogleAPIClient . I followed the tutorial for making the QuickStart app exactly.(http://stackoverflow.com/q/41454375/7120487)

**Comment by aytek** [comment]
Do you use pod for the Google libraries? Those libraries are already in the project scope, you may need to update them though.

**Comment by traviskaenel** [comment]
I believe so. Are you saying I don't need to import GoogleAPIClientForREST?

**Comment by aytek** [comment]
@traviskaenel At the time I built this project, Google libraries were not compatible with Pod. So I included them in the project. But I believe Google updated all of its libraries. You may not be able to use the old version. I recommend you to use without importing those libs. If it doesn't help, let me know please.
